name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install buildozer cython

      - name: Build APK
        working-directory: client
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: petraseu-apk
          path: client/bin/*.apk
